name: Release

on:
  push:
    branches:
      - 'master'

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # The Node.js version to configure
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run nx lint nx-serverless
        continue-on-error: true
      - name: Test
        run: npm run nx test nx-serverless
        continue-on-error: true

  bump-version:
    name: Version increment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # The Node.js version to configure
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
